### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by pixelwix** [MatthewFrench/Pokemap-Radar#1]
The Xcode projet fails to build!

`ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/AFNetworking'
ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/DDURLParser'
ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/ProtocolBuffers'
ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/UICKeyChainStore'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

Thats the error I get..

**Comment by MatthewFrench** [comment]
Did you follow the readme directions?

On Jul 28, 2016, at 10:18 PM, pixelwix <notifications@github.com<mailto:notifications@github.com>> wrote:


The Xcode projet fails to build!

ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/AFNetworking'
ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/DDURLParser'
ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/ProtocolBuffers'
ld: warning: directory not found for option '-L/Users/Michael/Library/Developer/Xcode/DerivedData/Pokemap-gvvwvonetwvbgigpuiksmqinpwlp/Build/Products/Debug-iphonesimulator/UICKeyChainStore'
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thats the error I get..

-

**Comment by pixelwix** [comment]
Yeah I followed all the instructions I was able to build the first build, this one is just giving me errors I tried to download and redo it same issues..

**Comment by MatthewFrench** [comment]
Works fine for me, fresh download and followed readme.

**Comment by pixelwix** [comment]
I just did that I'm telling you its looking for files that aren't there. I build this app when it was on the other repo that you cloned fine and I built the first commit that you uploaded alright, this new commit has errors?
